  - op: add
    path: /spec/steps/-
    value:
      name: annotate-task
      image: quay.io/redhat-appstudio/rhtap-task-runner:latest
      imagePullPolicy: Always
      script: |
        #!/usr/bin/env bash
        echo "verify-enterprise-contract $(context.taskRun.name)"
        oc annotate taskrun $(context.taskRun.name) task.results.format=application/json
        oc annotate taskrun $(context.taskRun.name) task.results.type=ec
        oc annotate taskrun $(context.taskRun.name) task.results.container=step-report-json
        oc annotate taskrun $(context.taskRun.name) task.output.location=logs
