apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
    build.appstudio.redhat.com/build_type: "docker"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "containers, rhtap"
  name: buildah-rhtap
spec:
  description: |-
    Buildah task builds source code into a container image and pushes the image into container registry using buildah tool.
    In addition it generates a SBOM file, injects the SBOM file into final container image and pushes the SBOM file as separate image using cosign tool.
  params:
  - description: Reference of the image buildah will produce.
    name: IMAGE
    type: string
  - default: ./Dockerfile
    description: Path to the Dockerfile to build.
    name: DOCKERFILE
    type: string
  - default: .
    description: Path to the directory to use as context.
    name: CONTEXT
    type: string
  - default: "true"
    description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
    name: TLSVERIFY
    type: string
  - name: BUILD_ARGS
    description: Array of --build-arg values ("arg=value" strings)
    type: array
    default: []
  - name: BUILD_ARGS_FILE
    description: Path to a file with build arguments, see https://www.mankier.com/1/buildah-build#--build-arg-file
    type: string
    default: ""
  - name: STORAGE_DRIVER
    description: Storage driver to configure for buildah
    type: string
    default: vfs
  results:
  - description: Digest of the image just built
    name: IMAGE_DIGEST
  - description: Image repository and tag where the built image was pushed
    name: IMAGE_URL
  - description: Digests of the base images used for build
    name: BASE_IMAGES_DIGESTS
  - description: Link to the SBOM layer pushed to the registry as part of an OCI artifact.
    name: SBOM_BLOB_URL
  stepTemplate:
    env:
    - name: HOMEDIR
      value: /home/tekton
    - name: STORAGE_DRIVER
      value: $(params.STORAGE_DRIVER)
    - name: CONTEXT
      value: $(params.CONTEXT)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE)
    - name: IMAGE
      value: $(params.IMAGE)
    - name: IMAGE_URL
      value: $(params.IMAGE)
    - name: TLSVERIFY
      value: $(params.TLSVERIFY)
    - name: BUILD_ARGS_FILE
      value: $(params.BUILD_ARGS_FILE)
    # TODO: These are requried by the init script but are not actually used by the buildah-rhtap.sh script
    - name: COSIGN_SECRET_PASSWORD
      value: ignore
    - name: COSIGN_SECRET_KEY
      value: ignore
    - name: COSIGN_PUBLIC_KEY
      value: ignore
    - name: DISABLE_ACS
      value: ignore
    - name: ROX_CENTRAL_ENDPOINT
      value: ignore
    - name: ROX_API_TOKEN
      value: ignore
    - name: GITOPS_AUTH_PASSWORD
      value: ignore
    - name: POLICY_CONFIGURATION
      value: ignore
    - name: REKOR_HOST
      value: ignore
    - name: IGNORE_REKOR
      value: ignore
    - name: INFO
      value: ignore
    - name: STRICT
      value: ignore
    - name: EFFECTIVE_TIME
      value: ignore
    workingDir: $(workspaces.source.path)
  steps:
  - name: build
    image: quay.io/redhat-appstudio/rhtap-task-runner:latest
    script: |
      # Workaround to make the init script work
      mkdir -p rhtap
      touch rhtap/env.sh
      # TODO: In case the env.sh file is missing, define expected env variables.
      export CUSTOM_ROOT_CA=''
      echo "Here's the env:"
      env

      /work/rhtap/init.sh

      /work/rhtap/buildah-rhtap.sh

# Step: init
# Results: /work/results/init
# /work/rhtap/common.sh: line 91: /work/rhtap/env.sh: No such file or directory
# ENV vars:
# Error: IMAGE_URL missing definition.
# Error: IMAGE missing definition.
# Error: COSIGN_SECRET_PASSWORD missing definition.
# Error: COSIGN_SECRET_KEY missing definition.
# Error: COSIGN_PUBLIC_KEY missing definition.
# Error: DISABLE_ACS missing definition.
# Error: ROX_CENTRAL_ENDPOINT missing definition.
# Error: ROX_API_TOKEN missing definition.
# Error: GITOPS_AUTH_PASSWORD missing definition.
# Error: POLICY_CONFIGURATION missing definition.
# Error: REKOR_HOST missing definition.
# Error: IGNORE_REKOR missing definition.
# Error: INFO missing definition.
# Error: STRICT missing definition.
# Error: EFFECTIVE_TIME missing definition.
# Error: HOMEDIR missing definition.
# Binaries:
# OK: git in /usr/bin/git
# OK: curl in /usr/bin/curl
# OK: jq in /usr/bin/jq
# OK: yq in /usr/bin/yq
# OK: buildah in /usr/bin/buildah
# OK: syft in /usr/bin/syft
# OK: cosign in /usr/bin/cosign
# OK: ec in /usr/bin/ec
# OK: python3 in /usr/bin/python3
# ---------- ERROR -----------------
# Errors in configuration above, fix and rerun
# Dependency Error  = 1
# Fatal Error code for  = 1
